/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RightsFactory } from "./RightsFactory";
export type { VideoRightsToken } from "./VideoRightsToken";
